# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kuntanury
email:            kuntanury@gmail.com
tagline:          'A Jekyll theme'
description:      "iOS Mobile Developer"
baseurl:          /

author:
  name:           'Kuntanury'
  url:            http://kuntanury.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

twitter_username: Kuntanury
github_username:  Kuntanury

# Site settings
title:            Kuntanury's Home Page
