# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            田坤
email:            kuntanury@gmail.com
tagline:          'Kuntanury blog'
description:      "iOS Mobile Developer"
baseurl:          /

author:
  name:           Kuntanury
  url:            "http://kuntanury.com"

github:
  repo:           https://github.com/Kuntanury/Kuntanury.github.io

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "page:num"

twitter_username: Kuntanury
github_username:  Kuntanury
